package com.demo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.demo.entity.Function;

public interface IFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    int insert(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    Function selectByPrimaryKey(Integer funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    List<Function> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Function record);

	List<Function> findMenu(@Param("userId")int userId);

	Function findByFuncName(String funcName);

	List<Function> findByParentId(int parentId);

	List<Function> findTreeByParentId(@Param("parentId") String parentId);
}