package com.demo.dao;

import com.demo.entity.UserRole;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("roleId") Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    List<UserRole> selectAll();
    
    /**
     * 根据用户id查询该用户所具有的角色
     * @param userId
     * @return
     */
    List<UserRole> findByUserId(@Param("userId") Integer userId);

	int deleteByUserId(@Param("userId") int userId);
}